### ISSUE TITLE
Unable to `enable_arc`

### ISSUE THREAD

**Issue by cswaney** [databricks-industry-solutions/auto-data-linkage#62]
Running the [notebooks/example.py](https://github.com/databricks-industry-solutions/auto-data-linkage/blob/main/python/arc/notebooks/example.py) on Databricks Runtime 13.3 ML throws a `py4j.Py4JException` within `arc.enable_arc`.

**Comment by robertwhiffin** [comment]
@cswaney -Docs updated, requires 12.2LTS ML runtime. Latest release does not require manually running enable_arc. please reach out if you would like to discuss your use case in more detail to robert.whiffin@databricks.com
